version: '3.8'
services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: postgres-lab4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: WEB_353502_LiubashenkaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.4.0
    container_name: pgadmin4-lab4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 5454
    ports:
      - "5454:5454"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: